export const actionTypes = {
  CONNECT_COMPONENT: 'MD_TRANSITION_CONNECT_COMPONENT',
  BODY_ELEMENT_CONNECT: 'MD_TRANSITION_BODY_ELEMENT_CONNECT',
  DISCONNECT_COMPONENT: 'MD_TRANSITION_DISCONNECT_COMPONENT',
  GROUP_WILL_UPDATE: 'MD_TRANSITION_GROUP_WILL_UPDATE',
  GROUP_DID_UPDATE: 'MD_TRANSITION_GROUP_DID_UPDATE',
  GROUP_GET_CHILD_REF: 'MD_TRANSITION_GROUP_GET_CHILD_REF',
  EVENT_RECORD_POSITION: 'MD_TRANSITION_EVENT_RECORD_POSITION',
  ANCHOR_GET_ELEM: 'MD_TRANSITION_ANCHOR_PREPARE_TRANS',
  COMMON_ELEMENT_GET_ELEM: 'MD_TRANSITION_COMMON_ELEMENT_GET_ELEM',
};
